import MiniChart from './MiniChart.jsx'
import { marketRows, onChainFlows, sentiment, macroEvents } from '../data/market.js'

/**
 * The small chart inside each research-input card.
 *
 * Four inputs, four different shapes, because they are four different kinds
 * of reading and drawing them identically would say they are the same thing:
 *
 *   chart      a price series          - continuous, two directions
 *   flows      bars around a baseline  - net inflow and outflow per hour
 *   sentiment  a position on a range   - where the market leans, not a value
 *   events     a schedule              - discrete moments, not a curve
 *
 * Every figure is generated by src/data/market.js, so each of these is
 * labelled illustrative by the card around it. None of them is decorative:
 * each one plots the data the card's text describes.
 */
export default function InputVisual({ kind }) {
  if (kind === 'chart') {
    const row = marketRows[0]
    return (
      <div className="iviz iviz--chart">
        <MiniChart
          series={row.series}
          stroke="var(--chart-up)"
          fill="var(--chart-up)"
          showBaseline
        />
      </div>
    )
  }

  if (kind === 'flows') {
    const peak = Math.max(...onChainFlows.map(Math.abs)) || 1
    return (
      <div className="iviz iviz--flows">
        <div className="flow-bars" role="img" aria-label="Net exchange flow, hourly, illustrative">
          {onChainFlows.map((v, i) => {
            // Half the height either side of the centre line, so an inflow and
            // an outflow of the same size read as the same magnitude in
            // opposite directions.
            const h = (Math.abs(v) / peak) * 50
            return (
              <span className="flow-bars__col" key={i}>
                <span
                  className={`flow-bars__bar${v >= 0 ? ' is-in' : ' is-out'}`}
                  style={{ height: `${h}%`, [v >= 0 ? 'bottom' : 'top']: '50%' }}
                />
              </span>
            )
          })}
          <span className="flow-bars__axis" aria-hidden="true" />
        </div>
      </div>
    )
  }

  if (kind === 'sentiment') {
    const { value, leftLabel, rightLabel, caption } = sentiment
    return (
      <div className="iviz iviz--sentiment">
        <div className="sentiment">
          <div
            className="sentiment__track"
            role="img"
            aria-label={`${caption}: ${value} out of 100 toward ${rightLabel}, illustrative`}
          >
            <span className="sentiment__fill" style={{ width: `${value}%` }} />
            <span className="sentiment__marker" style={{ left: `${value}%` }} />
          </div>
          <div className="sentiment__scale">
            <span>{leftLabel}</span>
            <span className="tnum">{value}</span>
            <span>{rightLabel}</span>
          </div>
        </div>
      </div>
    )
  }

  if (kind === 'events') {
    return (
      <div className="iviz iviz--events">
        <ul className="events">
          {macroEvents.map((e) => (
            <li key={e.label}>
              <span className="events__when tnum">{e.when}</span>
              <span className="events__label">{e.label}</span>
              <span className={`events__impact is-${e.impact.toLowerCase()}`}>{e.impact}</span>
            </li>
          ))}
        </ul>
      </div>
    )
  }

  return null
}
