import { drawdownSeries, drawdownPct } from '../data/market.js'

/**
 * The drawdown chart in the risk section.
 *
 * This is the one visual on the site that argues against the product, which
 * is why it exists: the section's entire claim is that the downside is stated
 * plainly, and a page that only ever draws rising lines is not doing that.
 *
 * The shaded band between the peak and the trough is the annotation that
 * matters - the percentage alone is abstract until it is shown as a width on
 * the chart. Hand-written SVG rather than MiniChart because the peak and
 * trough markers and the band have to be positioned against the same scale as
 * the line.
 *
 * The series is generated by src/data/market.js, hence the badge.
 */
const W = 320
const H = 120
const PAD = 10

/** Keeps a percentage-positioned label inside the card at either extreme. */
function anchor(ratio) {
  if (ratio > 0.78) return { transform: 'translateX(-100%)' }
  if (ratio < 0.22) return { transform: 'translateX(0)' }
  return { transform: 'translateX(-50%)' }
}

export default function RiskVisual() {
  const { points, peakIndex, troughIndex } = drawdownSeries
  const min = Math.min(...points)
  const max = Math.max(...points)
  const span = max - min || 1

  const x = (i) => (i / (points.length - 1)) * W
  const y = (v) => PAD + (1 - (v - min) / span) * (H - PAD * 2)

  const d = points.map((v, i) => `${i ? 'L' : 'M'} ${x(i).toFixed(2)} ${y(v).toFixed(2)}`).join(' ')
  const area = `${d} L ${W} ${H} L 0 ${H} Z`

  const peakX = x(peakIndex)
  const troughX = x(troughIndex)
  const bandX = Math.min(peakX, troughX)
  const bandW = Math.max(Math.abs(troughX - peakX), 1)

  return (
    <div className="risk-visual">
      <div className="risk-visual__head">
        <span className="badge-sample badge-sample--light">Risk</span>
      </div>

      <div className="risk-visual__chart">
        <svg
          className="chart"
          viewBox={`0 0 ${W} ${H}`}
          preserveAspectRatio="none"
          aria-hidden="true"
          focusable="false"
        >
          <defs>
            <linearGradient id="dd-fill" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor="var(--danger)" stopOpacity="0.22" />
              <stop offset="100%" stopColor="var(--danger)" stopOpacity="0" />
            </linearGradient>
          </defs>

          {/* The decline, called out as a region rather than left to be
              inferred from the shape of the line. */}
          <rect x={bandX} y={0} width={bandW} height={H} fill="var(--danger)" opacity="0.1" />

          <path d={area} fill="url(#dd-fill)" />
          {/* --danger, not --chart-down: the card is paper now, and the chart
              palette is tuned for the dark panels (6.38:1 vs 1.9:1 here). */}
          <path
            d={d}
            fill="none"
            stroke="var(--danger)"
            strokeWidth="2"
            strokeLinejoin="round"
            strokeLinecap="round"
            vectorEffect="non-scaling-stroke"
          />

          <circle cx={peakX} cy={y(points[peakIndex])} r="3.5" fill="var(--ink)" />
          <circle cx={troughX} cy={y(points[troughIndex])} r="3.5" fill="var(--danger)" />
        </svg>

        <div className="risk-visual__marks tnum">
          {/* Anchoring: a centred label at the far right of the chart would
              hang off the card, so the transform follows the position. */}
          <span style={{ left: `${(peakX / W) * 100}%`, ...anchor(peakX / W) }}>peak</span>
          <span style={{ left: `${(troughX / W) * 100}%`, ...anchor(troughX / W) }}>trough</span>
        </div>
      </div>

      <dl className="risk-visual__stats">
        <div>
          <dt>Max drawdown</dt>
          <dd className="tnum is-down">{drawdownPct.toFixed(1)}%</dd>
        </div>
        {/* The same move with borrowed exposure. This is the single clearest
            way to say what leverage does, and it uses the chart above. */}
        <div>
          <dt>Same move at 5×</dt>
          <dd className="is-down">More than the position is worth</dd>
        </div>
      </dl>
    </div>
  )
}
