import { useState } from 'react'
import { candles, marketRows, featuredMarket, TIMEFRAMES, formatPrice, formatChange } from '../data/market.js'

/**
 * A market dashboard for the About hero.
 *
 * This is the fullest view of the product on the site: a candlestick chart
 * over a row of market tiles. The homepage hero shows the same idea with a
 * line chart, and this deliberately draws candles instead - a dashboard with
 * a different chart type reads as a second view of the product rather than as
 * the same panel moved to another page.
 *
 * Everything here is generated by src/data/market.js, hence the badge. The
 * candles come from the same series the closing CTA draws, windowed by the
 * timeframe control.
 */
const W = 460
const H = 190
const PAD = 12

const WINDOW = { '1H': 16, '1D': 28, '1W': 40, '1M': 52 }

export default function TradingDashboard() {
  const [timeframe, setTimeframe] = useState('1D')
  const series = candles.slice(-(WINDOW[timeframe] ?? 28))

  const max = Math.max(...series.map((c) => c.high))
  const min = Math.min(...series.map((c) => c.low))
  const span = max - min || 1

  const y = (v) => PAD + (1 - (v - min) / span) * (H - PAD * 2)
  const slot = W / series.length
  const bodyW = Math.max(slot * 0.5, 2.5)

  const up = featuredMarket.change >= 0

  return (
    <div className="dashboard">
      <div className="dashboard__head">
        <span className="badge-sample">
          <span className="badge-sample__dot" aria-hidden="true" />
          Live view · illustrative
        </span>
        <span className="dashboard__market">{featuredMarket.market}</span>
      </div>

      <div className="dashboard__quote">
        <div>
          <p className="dashboard__symbol">{featuredMarket.symbol}</p>
          <p className="dashboard__name">{featuredMarket.name}</p>
        </div>
        <div className="dashboard__figures">
          <p className="dashboard__value tnum">${formatPrice(featuredMarket.price)}</p>
          <p className={`dashboard__change tnum${up ? ' is-up' : ' is-down'}`}>
            <span aria-hidden="true">{up ? '▲' : '▼'}</span> {formatChange(featuredMarket.change)}
            <span className="dashboard__period"> today</span>
          </p>
        </div>
      </div>

      <div className="dashboard__chart">
        <svg
          className="chart"
          viewBox={`0 0 ${W} ${H}`}
          preserveAspectRatio="none"
          aria-hidden="true"
          focusable="false"
        >
          <g stroke="var(--chart-grid)" strokeWidth="1" strokeDasharray="3 5">
            {[0, 1, 2, 3].map((i) => (
              <line key={i} x1="0" x2={W} y1={PAD + (i * (H - PAD * 2)) / 3} y2={PAD + (i * (H - PAD * 2)) / 3} />
            ))}
          </g>

          {series.map((c, i) => {
            const x = i * slot + slot / 2
            const rising = c.close >= c.open
            const stroke = rising ? 'var(--chart-up)' : 'var(--chart-down)'
            const top = y(Math.max(c.open, c.close))
            const bottom = y(Math.min(c.open, c.close))
            return (
              <g key={i} stroke={stroke} fill={stroke}>
                <line x1={x} x2={x} y1={y(c.high)} y2={y(c.low)} strokeWidth="1.1" />
                <rect x={x - bodyW / 2} y={top} width={bodyW} height={Math.max(bottom - top, 1.5)} rx="0.8" />
              </g>
            )
          })}
        </svg>
      </div>

      <div className="dashboard__timeframes" role="group" aria-label="Chart timeframe">
        {TIMEFRAMES.map((tf) => (
          <button
            key={tf}
            type="button"
            className={`tf${tf === timeframe ? ' is-active' : ''}`}
            aria-pressed={tf === timeframe}
            onClick={() => setTimeframe(tf)}
          >
            {tf}
          </button>
        ))}
      </div>

      <ul className="dashboard__tiles">
        {marketRows.slice(1, 5).map((row) => (
          <li key={row.key}>
            <span className="dashboard__tile-symbol">{row.symbol}</span>
            <span className={`dashboard__tile-change tnum${row.change >= 0 ? ' is-up' : ' is-down'}`}>
              {formatChange(row.change)}
            </span>
          </li>
        ))}
      </ul>
    </div>
  )
}
