// Converts supplied images from source-images/ into public/*.webp.
//
//   npm run images
//
// The site's own artwork is generated by make-og.mjs and
// make-illustrations.mjs; this handles the images that arrive from outside -
// photographs and illustrations supplied by hand.
//
// WHY THE SOURCES ARE NOT IN public/. Everything in public/ is copied into
// dist/ verbatim, so a 1.5 MB PNG sitting there ships on every deploy even
// though the page loads the WebP. The four supplied about images were 6.2 MB
// of the 12 MB the build produced. They live in source-images/ instead, which
// Vite does not copy - the originals are kept for re-deriving, and only the
// converted output is published.
import { readdirSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = path.join(ROOT, 'source-images')
const PUBLIC = path.join(ROOT, 'public')

const QUALITY = 82
/** Wider than this is wasted: nothing on the site displays an image past
 *  ~700 CSS px, so 1400 covers a 2x screen and no more. */
const MAX_WIDTH = 1400

const kb = (n) => `${(n / 1024).toFixed(0)} KB`

async function main() {
  let sources = []
  try {
    sources = readdirSync(SOURCE).filter((f) => /\.(png|jpe?g)$/i.test(f))
  } catch {
    console.log('no source-images/ directory')
    return
  }

  if (!sources.length) {
    console.log('nothing in source-images/ to convert')
    return
  }

  let before = 0
  let after = 0

  for (const file of sources) {
    const src = path.join(SOURCE, file)
    const name = path.basename(file, path.extname(file))
    const out = path.join(PUBLIC, `${name}.webp`)

    const original = statSync(src).size
    const meta = await sharp(src).metadata()
    const resize = meta.width > MAX_WIDTH ? { width: MAX_WIDTH } : {}

    const webp = await sharp(src).resize(resize).webp({ quality: QUALITY, effort: 6 }).toBuffer()
    writeFileSync(out, webp)

    before += original
    after += webp.length
    console.log(
      `${file.padEnd(16)} ${String(meta.width).padStart(5)}x${String(meta.height).padEnd(5)} ${kb(original).padStart(7)} -> ${kb(webp.length).padStart(6)}  ->  public/${name}.webp`,
    )
  }

  console.log(`\n${sources.length} image(s): ${kb(before)} -> ${kb(after)}`)
}

main().catch((e) => {
  console.error(e.message)
  process.exit(1)
})
